[build.environment]
NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm run build:vite"

[[redirects]]
  from = "/@api/*"
  to = "https://api.besscroft.com/@api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { not = [ { path = "/@api/*" } ] }

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
