name: "Vite CI with Multi-arch Docker Test Image"

on:
  push:
    branches:
      - dev

jobs:
  docker:
    name: Running Compile Vite Multi-arch Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout diyfile-web
        uses: actions/checkout@v3
      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: corepack enable
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm i
      - run: pnpm run build:vite
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push diyfile web test
        id: docker_build_diyfile_web_test
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./.github/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diyfile-web:test
